### ISSUE TITLE
Rudderstack error in android release version

### ISSUE THREAD

**Issue by brizaldi** [rudderlabs/rudder-sdk-flutter#37]
Hi, I've got this error whenever I try to minimize the app (press home button in Android). After that when I back to my app, the app will restart to the beginning.

This error only happened in release build though, in debug mode the app is working fine.

rudder_sdk_flutter: ^1.2.0
flutter: 2.5.3

```
E/AndroidRuntime(19455): FATAL EXCEPTION: main
E/AndroidRuntime(19455): Process: com.evermos.evm.stag, PID: 19455
E/AndroidRuntime(19455): java.lang.RuntimeException: Unable to stop activity {com.vnotes.app.stag/com.vnotes.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.rudderstack.android.sdk.core.RudderContext com.rudderstack.android.sdk.core.RudderContext.copy()' on a null object reference
E/AndroidRuntime(19455):        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4856)
E/AndroidRuntime(19455):        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4827)
E/AndroidRuntime(19455):        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4901)
E/AndroidRuntime(19455):        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
E/AndroidRuntime(19455):        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(19455):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(19455):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(19455):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19455):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(19455):        at android.app.ActivityThread.main(ActivityThread.java:7664)
E/AndroidRuntime(19455):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19455):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(19455):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(19455): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.rudderstack.android.sdk.core.RudderContext com.rudderstack.android.sdk.core.RudderContext.copy()' on a null object reference
E/AndroidRuntime(19455):        at com.rudderstack.android.sdk.core.RudderElementCache.getCachedContext(Unknown Source:2)
E/AndroidRuntime(19455):        at com.rudderstack.android.sdk.core.RudderMessage.<init>(Unknown Source:58)
E/AndroidRuntime(19455):        at com.rudderstack.android.sdk.core.RudderMessageBuilder.build(Unknown Source:2)
E/AndroidRuntime(19455):        at com.rudderstack.android.sdk.core.RudderClient.track(Unknown Source:16)
E/AndroidRuntime(19455):        at C2.c.b(:1)
E/AndroidRuntime(19455):        at C2.b.run(Unknown Source:0)
E/AndroidRuntime(19455):        at C2.c.onActivityStopped(Unknown Source:18)
E/AndroidRuntime(19455):        at android.app.Application.dispatchActivityStopped(Application.java:496)
E/AndroidRuntime(19455):        at android.app.Activity.dispatchActivityStopped(Activity.java:1445)
E/AndroidRuntime(19455):        at android.app.Activity.onStop(Activity.java:2591)
E/AndroidRuntime(19455):        at io.flutter.embedding.android.f.onStop(Unknown Source:0)
E/AndroidRuntime(19455):        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1482)
E/AndroidRuntime(19455):        at android.app.Activity.performStop(Activity.java:8209)
E/AndroidRuntime(19455):        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4848)
E/AndroidRuntime(19455):        ... 12 more
```

**Comment by brizaldi** [comment]
Update: After setting `builder.withTrackLifecycleEvents` to `false` the error isn't happening anymore.
Any clue how to fix this?

**Comment by pallabmaiti** [comment]
Hi @brizaldi Thanks for raising the issue. We will look into it.

**Comment by desusai7** [comment]
Hey @brizaldi, 
We tried reproducing this issue but couldn't. Can you help us with the information on how you are doing the below things to help us better debug this:
i) Initializing the Rudder Flutter SDK. If possible please share the SDK Initialization snippet. 
ii) Making calls like Identify, Track. Again If possible please share an example of the same.
iii) Are you trying to make any operation on minimizing the application?
iv) Are there any changes in the building of release build, like any additional proguard rules etc.. ?
v) Were the events sent to Rudderstack successful before minimizing the application ?
vi) Any specific android device on which this is happening ?

**Comment by brizaldi** [comment]
Were using GetX in our app:

In the initial binding:
```dart
Get.put<Rudderstack>(
  Rudderstack(
    writeKey: RUDDER_WRITE_KEY,
    config: Rudderstack.defaultConfig(
      isWithTrackLifecycleEvents: true,
      logLevel: RudderLogger.INFO,
      dataPlaneUrl: 'https://rudderstack.ourdomain.com,
    ),
  ),
);
```

Our `rudderstack.dart` class:
```dart
class Rudderstack {
  Rudderstack({
    RudderConfig? config,
    RudderOption? options,
    required String writeKey,
  }) {
    client.initialize(
      writeKey,
      config: config,
      options: options,
    );
  }

  final client = RudderClient.instance;

  static RudderConfig defaultConfig({
    required String dataPlaneUrl,
    int flushQueueSize = 30,
    bool isWithTrackLifecycleEvents = true,
    int? logLevel,
    int sleepCount = 10,
  }) {
    final builder = RudderConfigBuilder();
    builder.withDataPlaneUrl(dataPlaneUrl);
    builder.withTrackLifecycleEvents(isWithTrackLifecycleEvents);
    builder.withLogLevel(logLevel ?? RudderLogger.DEBUG);
    builder.withFlushQueueSize(flushQueueSize);
    builder.withSleepCount(sleepCount);
    return builder.build();
  }

  void track({
    required String event,
    RudderProperty? properties,
    RudderOption? options,
  }) => client.track(event, properties: properties, options: options);

  // other rudderstack method
  // ...
}
```

**Comment by brizaldi** [comment]
iii) Are you trying to make any operation on minimizing the application?
No
iv) Are there any changes in the building of release build, like any additional proguard rules etc.. ?
No
v) Were the events sent to Rudderstack successful before minimizing the application ?
Yes, the other rudderstack event (track, identify, etc) are sent successfully
vi) Any specific android device on which this is happening ?
It is happening on all our test devices

**Comment by desusai7** [comment]
Hey @brizaldi, 

Thank you for sharing the information. We tried reproducing the issue with the details you had provided as shown below, but we couldn't see any crashes on closing the app and all the events are flowing successfully. 

We are suspecting some proguard rules are resulting in this issue, as it is happening only on release versions. Can you please share your proguard rules if possible ?

And also can you check the code snippet attached below and let us know, if we are missing any step in the process to reproduce the issue ? 

```dart
void main() => runApp(GetMaterialApp(home: Home()));

class Home extends StatelessWidget {
  @override
  Widget build(context) {
    
    final Rudderstack c = Get.put<Rudderstack>(
      Rudderstack(
        writeKey: "22g6gL9jG5QeNmYJeWjdSMhvr5J",
        config: Rudderstack.defaultConfig(
            isWithTrackLifecycleEvents: true, logLevel: RudderLogger.INFO),
      ),
    );

    c.track(event: "Main screen");

    return Scaffold(
        appBar: AppBar(title: Obx(() => Text("Clicks: ${c.count}"))),

        body: Center(
            child: ElevatedButton(
                child: Text("Go to Other"), onPressed: () => Get.to(Other()))),
        floatingActionButton: FloatingActionButton(
            child: Icon(Icons.add), onPressed: c.increment));
  }
}

class Other extends StatelessWidget {
  final Rudderstack c = Get.find();

  @override
  Widget build(context) {
    Get.find<Rudderstack>().track(event: "Other Screen");
    return Scaffold(body: Center(child: Text("${c.count}")));
  }
}

class Rudderstack extends GetxController {
  Rudderstack({
    RudderConfig? config,
    RudderOption? options,
    required String writeKey,
  }) {
    client.initialize(
      writeKey,
      config: config,
      options: options,
    );
  }

  var count = 0.obs;
  increment() => count++;

  final client = RudderClient.instance;

  static RudderConfig defaultConfig({
    String? dataPlaneUrl,
    int flushQueueSize = 30,
    bool isWithTrackLifecycleEvents = true,
    int? logLevel,
    int sleepCount = 10,
  }) {
    final builder = RudderConfigBuilder();
    // dataPlaneUrl ?? builder.withDataPlaneUrl(dataPlaneUrl);
    builder.withTrackLifecycleEvents(isWithTrackLifecycleEvents);
    builder.withLogLevel(logLevel ?? RudderLogger.DEBUG);
    builder.withFlushQueueSize(flushQueueSize);
    builder.withSleepCount(sleepCount);
    return builder.build();
  }

  void track({
    required String event,
    RudderProperty? properties,
    RudderOption? options,
  }) =>
      client.track(event, properties: properties, options: options);
}
```

**Comment by pallabmaiti** [comment]
Hey @brizaldi can you give us the necessary information?

**Comment by brizaldi** [comment]
Hi, sorry for late reply, were currently not using any proguard rules on our app

**Comment by desusai7** [comment]
Okay. We tried reproducing it with the above snippet attached, but we couldn't. Can you please provide us with a minor reproducible example app, so that we can take this forward?

**Comment by chandrabezzo** [comment]
Hi @desusai7, @brizaldi is my colleague. You need to use `Get.put` under bindings class, please follow best practice implementation using GetX state management. Call the binding under `GetMaterialApp` at `initialBinding`.

**Comment by desusai7** [comment]
Hey @chandrabezzo, Thank you for pointing it out, we will make the changes and check

**Comment by desusai7** [comment]
Hey @chandrabezzo & @brizaldi,

We had implemented the changes you had suggested i.e moving `Get.put` to `bindings` class and calling that binding under `GetMaterialApp` at `initialBinding` and then testing it with debug release couldn't find the issue. 

Then went ahead and created the `release` build and then tested it on android emulators as well as various real devices by clicking on the Home Button to minimize the app as well as consecutively tapping on the back button to minimize the app. 

But in none of the cases, we were able to reproduce the issue. 

With the changes, you had suggested our `main.dart` files looks as below, please check that and let me know if we were doing anything different from your setup which might be the reason for the issue. 

Also for better and quicker support, we would request you to provide us with a minor reproducible version of the issue.


```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:rudder_sdk_flutter/RudderClient.dart';
import 'package:rudder_sdk_flutter/RudderConfig.dart';
import 'package:rudder_sdk_flutter/RudderLogger.dart';
import 'package:rudder_sdk_flutter/RudderOption.dart';
import 'package:rudder_sdk_flutter/RudderProperty.dart';

void main() =>
    runApp(GetMaterialApp(home: Home(), initialBinding: HomeBinding()));

class RudderController {
  RudderController({
    RudderConfig? config,
    RudderOption? options,
    required String writeKey,
  }) {
    client.initialize(
      writeKey,
      config: config,
      options: options,
    );
  }
  final count = 0;
  final client = RudderClient.instance;

  static RudderConfig defaultConfig({
    String? dataPlaneUrl,
    int flushQueueSize = 30,
    bool isWithTrackLifecycleEvents = true,
    int? logLevel,
    int sleepCount = 10,
  }) {
    final builder = RudderConfigBuilder();
    builder.withTrackLifecycleEvents(isWithTrackLifecycleEvents);
    builder.withLogLevel(logLevel ?? RudderLogger.DEBUG);
    builder.withFlushQueueSize(flushQueueSize);
    builder.withSleepCount(sleepCount);
    return builder.build();
  }

  void track({
    required String event,
    RudderProperty? properties,
    RudderOption? options,
  }) =>
      client.track(event, properties: properties, options: options);
}

class HomeBinding implements Bindings {
  @override
  void dependencies() {
    Get.put<RudderController>(RudderController(
        writeKey: "1rC6xZFSesTnCG8UT1s6AOQmOvD",
        config: RudderController.defaultConfig(
            isWithTrackLifecycleEvents: false, logLevel: RudderLogger.NONE)));
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(context) {
    final RudderController c = Get.find();
    c.track(event: "Main screen");
    return Scaffold(
        appBar: AppBar(title: Text("Home Screen")),
        body: Center(
            child: ElevatedButton(
                child: Text("Go to Other"), onPressed: () => Get.to(Other()))));
  }
}

class Other extends StatelessWidget {
  @override
  Widget build(context) {
    final RudderController c = Get.find();
    c.track(event: "From Other screen");
    return Scaffold(body: Center(child: Text("Other Screen")));
  }
}

```

**Comment by pallabmaiti** [comment]
Hey @brizaldi & @chandrabezzo can we setup a meeting to debug this? Otherwise, we can't reproduce in our end.

**Comment by brizaldi** [comment]
After upgrading to Flutter 2.8.1 and creating a new project based on that version of Flutter, somehow the error is now gone.
Closing this issue now. Thank you @Rudderlabs team.

**Comment by desusai7** [comment]
We heard from @chandrabezzo that this issue is caused by some dependency conflicts in @chandrabezzo's setup. This was solved by him following the below steps:

1. Created a new project using Flutter 2.8.1 
2. Deleting the `android` module of the Flutter project 
3. And then creating it again by running `flutter create .`

Closing this issue for now, in case anyone faces a similar issue in the future feel free to re-open it.
