### ISSUE TITLE
Error StandardMethodCodec.java line 607 StandardMethodCodec.decodeEnvelope

### ISSUE THREAD

**Issue by chandrabezzo** [rudderlabs/rudder-sdk-flutter#38]
We try to publish android app using Rudder Stack. Our Firebase Crashlytics record non-fatal issue, but in the screen affected change widget to blank white.

Below the title error information from crashlytics:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(error, Attempt to invoke virtual method 'com.rudderstack.android.sdk.core.RudderContext com.rudderstack.android.sdk.core.RudderContext.copy()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'com.rudderstack.android.sdk.core.RudderContext com.rudderstack.android.sdk.core.RudderContext.copy()' on a null object reference at com.rudderstack.android.sdk.core.RudderElementCache.getCachedContext(Unknown Source:2) at com.rudderstack.android.sdk.core.RudderMessage.<init>(Unknown Source:58) at com.rudderstack.android.sdk.core.RudderMessageBuilder.build(Unknown Source:2) at com.rudderstack.android.sdk.core.RudderClient.track(Unknown Source:24) at D2.d.onMethodCall(:4) at R2.c.a(:4) at G2.i.h(Unknown Source:11) at G2.i.g(:3) at G2.e.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7562) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) ). Error thrown null.
```

Below detail error information from crashlytics:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Attempt to invoke virtual method 'com.rudderstack.android.sdk.core.RudderContext com.rudderstack.android.sdk.core.RudderContext.copy()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'com.rudderstack.android.sdk.core.RudderContext com.rudderstack.android.sdk.core.RudderContext.copy()' on a null object reference
	at com.rudderstack.android.sdk.core.RudderElementCache.getCachedContext(Unknown Source:2)
	at com.rudderstack.android.sdk.core.RudderMessage.<init>(Unknown Source:58)
	at com.rudderstack.android.sdk.core.RudderMessageBuilder.build(Unknown Source:2)
	at com.rudderstack.android.sdk.core.RudderClient.track(Unknown Source:24)
	at D2.d.onMethodCall(:4)
	at R2.c.a(:4)
	at G2.i.h(Unknown Source:11)
	at G2.i.g(:3)
	at G2.e.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(StandardMethodCodec.java:607)
       at MethodChannel._invokeMethod(MethodChannel.java:167)
```

I think this problem under Android Native SDK that connected with flutter plugin. Or I implement the wrong approach to track using Rudderstack?

**Comment by chandrabezzo** [comment]
This the information when I run command `flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale en-ID)
    • Flutter version 2.8.1 at /Users/bezzo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bezzo/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  •
      Android 11 (API 30) (emulator)
    • iPhone 8 (mobile)         • 31C4E0A9-955F-4723-A41E-77F91C419CE4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)              • chrome                               • web-javascript •
      Google Chrome 96.0.4664.110

• No issues found!
```

**Comment by chandrabezzo** [comment]
This information about device that got the problem
<img width="1004" alt="Screen Shot 2021-12-31 at 10 09 03" src="https://user-images.githubusercontent.com/16184998/147800883-795710d8-1023-4539-b5e0-4f1ef4d580cb.png">

**Comment by desusai7** [comment]
Hey @chandrabezzo, Thank you for sharing the issue we will check this and get back to you

**Comment by chandrabezzo** [comment]
Hi @desusai7 thank you for the response. I will wait the feedback from Rudderstack team.

**Comment by chandrabezzo** [comment]
Fixed when you use latest platform setup in Flutter 2.8.1
